name: 'Parse Deploy Config'
description: 'Parse and return active deployment configuration for a given environment and region'
inputs:
  config:
    description: 'Path to config JSON'
    required: true
  env:
    description: 'Environment (e.g. dev, prod)'
    required: true
  region:
    description: 'Region (use1, usw2, etc.)'
    required: true
  delimiter:
    description: 'Delimiter for flattening (default .)'
    required: false
    default: '.'

runs:
  using: 'node20'
  main: 'dist/index.js'
