name: 'Parse Deploy Config'
description: 'Parse and return active deployment configuration for a given environment and region'
inputs:
  config:
    description: 'Path to config JSON'
    required: true
  env:
    description: 'Environment (e.g. dev, prod)'
    required: true
  region:
    description: 'Region (use1, usw2, etc.)'
    required: true
  delimiter:
    description: 'Delimiter for flattening (default .)'
    required: false
    default: '.'
outputs:
  config:
    description: "Merged config as a list of values (eg: outputs['component.nestedSetting'] - must use bracket notation to access)"
runs:
  using: 'node20'
  main: 'index.js'
